name: rPlace
author: D151l
version: 1.0.2
api-version: 1.13

main: de.d151l.place.plugin.plugin.SpigotPlugin

commands:
  removeBlock:
    permission: place.command.remove.block
  checkBlock:
    permission: place.command.check.block
  rplace:
    permission: place.command.rplace